from enum import Enum


class MLBTeams(Enum):
    ARIZONA_DIAMONDBACKS = "ARI"
    ATLANTA_BRAVES = "ATL"
    BALTIMORE_ORIOLES = "BAL"
    BOSTON_RED_SOX = "BOS"
    CHICAGO_CUBS = "CHC"
    CHICAGO_WHITE_SOX = "CHW"
    CINCINNATI_REDS = "CIN"
    CLEVELAND_INDIANS = "CLE"
    COLORADO_ROCKIES = "COL"
    DETROIT_TIGERS = "DET"
    HOUSTON_ASTROS = "HOU"
    KANSAS_CITY_ROYALS = "KCR"
    LOS_ANGELES_ANGELS_OF_ANAHEIM = "LAA"
    LOS_ANGELES_DODGERS = "LAD"
    MIAMI_MARLINS = "MIA"
    MILWAUKEE_BREWERS = "MIL"
    MINNESOTA_TWINS = "MIN"
    NEW_YORK_METS = "NYM"
    NEW_YORK_YANKEES = "NYY"
    OAKLAND_ATHLETICS = "OAK"
    PHILADELPHIA_PHILLIES = "PHI"
    PITTSBURGH_PIRATES = "PIT"
    SAN_DIEGO_PADRES = "SDP"
    SAN_FRANCISCO_GIANTS = "SFG"
    SEATTLE_MARINERS = "SEA"
    ST_LOUIS_CARDINALS = "STL"
    TAMPA_BAY_RAYS = "TBR"
    TEXAS_RANGERS = "TEX"
    TORONTO_BLUE_JAYS = "TOR"
    WASHINGTON_NATIONALS = "WSN"


class MLBParks(Enum):
    ARIZONA_DIAMONDBACKS = "Chase Field"
    ATLANTA_BRAVES = "Truist Park"
    BALTIMORE_ORIOLES = "Camden Yards"
    BOSTON_RED_SOX = "Fenway Park"
    CHICAGO_CUBS = "Wrigley Field"
    CHICAGO_WHITE_SOX = "Guaranteed Rate Field"
    CINCINNATI_REDS = "Great American Ballpark"
    CLEVELAND_INDIANS = "Progressive Field"
    COLORADO_ROCKIES = "Coors Field"
    DETROIT_TIGERS = "Comerica Park"
    HOUSTON_ASTROS = "Minute Maid Park"
    KANSAS_CITY_ROYALS = "Kauffman Stadium"
    LOS_ANGELES_ANGELS_OF_ANAHEIM = "Angel Stadium"
    LOS_ANGELES_DODGERS = "Dodger Stadium"
    MIAMI_MARLINS = "LoanDepot Park"
    MILWAUKEE_BREWERS = "American Family Field"
    MINNESOTA_TWINS = "Target Field"
    NEW_YORK_METS = "Citi Field"
    NEW_YORK_YANKEES = "Yankee Stadium"
    OAKLAND_ATHLETICS = "Oakland Coliseum "
    PHILADELPHIA_PHILLIES = "Citizens Bank Park"
    PITTSBURGH_PIRATES = "PNC Park"
    SAN_DIEGO_PADRES = "Petco Park"
    SAN_FRANCISCO_GIANTS = "Oracle Park"
    SEATTLE_MARINERS = "T-Mobile Park"
    ST_LOUIS_CARDINALS = "Busch Stadium"
    TAMPA_BAY_RAYS = "Tropicana Field"
    TEXAS_RANGERS = "Globe Life Field"
    TORONTO_BLUE_JAYS = "Rogers Centre"
    WASHINGTON_NATIONALS = "Nationals Park"
